// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function twoFer(input) {
  return "One for " + (Belt_Option.getWithDefault(input, "you") + ", one for me.");
}

exports.twoFer = twoFer;
/* No side effect */
